### ISSUE TITLE
sugestão de validação de caracteres especiais

### ISSUE THREAD

**Issue by jampow** [lvolcov/BolOscar2021#1]
Pelo o que entendi só pode letras, números e espaços no nome, certo? Se for esse o caso poderia validar só o que é valido, pois são menos casos do que os inválidos. Seria algo como:

```javascript
// Qualquer coisa q não seja uma letra, número ou espaço
const regex = /[^a-z0-9 ]/gi;
```

https://github.com/lvolcov/BolOscar2021/blob/87f7afe3c387bc9a1863e7aaaecc208687b974e0/functions/validateAnswer.js#L3

**Comment by jampow** [comment]
se vc está evitando isso para evitar alguma forma de injeção de código, uma outra saída é escapar (ou sanitizar) os caracteres especiais.

**Comment by lvolcov** [comment]
Sugestão de regex alternativo implementada na função validateAnswer, que filtra todos os inputs dos usuários que são considerados pelo bot.
