### ISSUE TITLE
cuidado com sql injection

### ISSUE THREAD

**Issue by jampow** [lvolcov/BolOscar2021#2]
Sei que a interface é um bot do telegram, mas se eu colocar um sniffer na rede posso ver a requisição indo para o bot e se vc está pegando o valor da requisição e colocando ela direto na query está muito fácil de fazer um sql injection e prejudicar todo o negócio. Vale a pena sanitizar esse input só por segurança.

https://github.com/lvolcov/BolOscar2021/blob/87f7afe3c387bc9a1863e7aaaecc208687b974e0/functions/sqlResources/updateWinnersTable.js#L10

**Comment by jampow** [comment]
imagina que eu vi uma requisição saindo assim: `https://telegram.org/bot-api/?vencedor=lucas`. Aí vc pega esse valor lucas e coloca direto no banco. Agora se eu mandar `gian"; --` eu já manipulei a query para que eu ganhe em todas as categorias. ou pior, poderia apagar o banco `"; drop database; --`

**Comment by lvolcov** [comment]
Seguindo o issue #4 , knex foi implementado em todas as funções SQL do projeto, o que deve resolver isso.
