### ISSUE TITLE
abstrair a conexão

### ISSUE THREAD

**Issue by jampow** [lvolcov/BolOscar2021#3]
Vc repete a abertura de conexão em todos os arquivos, pode ter um arquivo q exporta a conexão para vc.

```javascript
// arquivo dbconnection.js
const mysql = require('mysql');
const con = mysql.createConnection({
    host: process.env.HOST,
    user: process.env.USER,
    password: process.env.PASSWORD,
    database: process.env.DATABASE
});
export.default = con;
```
Aí nesse arquivo aqui embaixo vc pode só importar o dbconection.

https://github.com/lvolcov/BolOscar2021/blob/87f7afe3c387bc9a1863e7aaaecc208687b974e0/functions/sqlResources/updateWinnersTable.js#L4

**Comment by lvolcov** [comment]
criado arquivo que exporta a conexao ✅✅✅
