### ISSUE TITLE
para criação e manutenção, inclusive queries...

### ISSUE THREAD

**Issue by jampow** [lvolcov/BolOscar2021#4]
para trabalhar com bancos de dados relacionais eu aconselho uma lib como o [knexjs](http://knexjs.org/), ela é um query builder e vem com migrações para versionar o banco de dados e sua evolução. evita alguns dos problemas citados nas issues anteriores ce sql injection e pode trabalhar com vários tipos de banco de dados.

https://github.com/lvolcov/BolOscar2021/blob/87f7afe3c387bc9a1863e7aaaecc208687b974e0/functions/sqlResources/createTable.sql#L1

**Comment by lvolcov** [comment]
Implementei knex em todas as funcões SQL do projeto ✅✅✅
